---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pltliont/public_html/eye-tracking-look-to-speak-web
    - /bin/cp main.py $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
